file = open('Intro1.txt','w')
file.write("Hello! ")
file.writelines(["I am BLA BLA\n","I read in STCET.\n", "I study. \n"])
file.close()
file = open('Intro1.txt','r')
print(file.read())
file.close()
file = open('Intro1.txt','r')
print(file.readline())
print(file.readline())
print(file.readline(5))
file.close()
f = open('Intro1.txt','r')  
for line in f.readlines():
    print(line)
f.close()
